theme: jekyll-theme-cayman
title: Labs for Capella
email: labs4capella@gmail.com
description: >
  Labs for Capella aims at providing the Eclipse Capella ecosystem
  with a creativity and innovation space. It is the place where Capella
  users, as well as tool providers, can collaborate and create synergies
  to develop Capella add-ons, from the incubation state, with the option
  to reach an industrial level. Today Labs for Capella allows you to share
  your Capella add-ons, and to use those shared by others.
